# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- will-jekyll-template


sudo apt-get install rubygems

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true

stages:
- stage: BuildPoanchenPersonalWebsite
  jobs:
  - job: UseRuby
    steps:
    - task: UseRubyVersion@0
  - job: InstallDependency
    dependsOn: UseRuby
    steps:
    - script: gem install jekyll-sitemap wdm
  - job: BuildJekyll
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: InstallDependency
    steps:
    - task: Docker@0
      displayName: 'Run Jekyll'
      inputs:
        containerRegistryType: 'Container Registry'
        action: 'Run an image'
        imageName: 'jekyll/builder:latest'
        volumes: |
          $(build.sourcesDirectory):/srv/jekyll
          $(build.binariesDirectory):/srv/jekyll/_site
        containerCommand: 'jekyll build'
        detached: false
